install.packages("OpenImageR")
install.packages("dplyr")
install.packages("glmnet")
install.packages("e1071")
install.packages("nnet")
install.packages("caret")
install.packages("doParallel")
install.packages("kernlab")